#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/docker/simulators"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/docker/simulators/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/docker/uncertainpy/examples/interneuron/interneuron_model/x86_64/.libs/libnrnmech.so" "$@"
