FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Python prerequisites
RUN apt-get update --fix-missing
RUN apt-get -y install python3-pip software-properties-common > /dev/null


ENV HOME=/home/docker
ENV VENV=$HOME/simulators
RUN mkdir $HOME; mkdir $HOME/packages; mkdir $VENV

# Nest dependencies
RUN apt-get install -y \
    cython \
    libgsl-dev \
    libltdl-dev \
    libncurses-dev \
    libreadline-dev \
    python-all-dev \
    python-nose \
    openmpi-bin \
    libopenmpi-dev \
    cmake


# Install Nest
ENV NEST_VER=2.20.0
ENV NEST=nest-$NEST_VER

WORKDIR $HOME/packages
ADD https://github.com/nest/nest-simulator/archive/v$NEST_VER.tar.gz .
RUN tar xzf v$NEST_VER.tar.gz; rm v$NEST_VER.tar.gz

RUN mkdir $VENV/build; mkdir $VENV/build/$NEST; mkdir $VENV/bin

WORKDIR $VENV/build/$NEST
RUN cmake -DCMAKE_INSTALL_PREFIX=$VENV \
          -Dwith-mpi=ON -Dwith-python=3 \
          $HOME/packages/nest-simulator-$NEST_VER > /dev/null
RUN make
RUN make install > /dev/null

WORKDIR /home/docker/
RUN echo "source $VENV/bin/nest_vars.sh" >> .bashrc
# Add nest to python path
ENV PYTHONPATH $PYTHONPATH:/home/docker/simulators/lib/python3.6/site-packages/

# Neuron dependencies
RUN apt-get install -y libx11-dev git bison flex automake libtool libxext-dev \
    libncurses-dev python3-dev xfonts-100dpi cython3 libopenmpi-dev make zlib1g-dev > /dev/null

# Install Neuron
ENV PATH=$PATH:$VENV/bin

ENV NRN_VER=7.7
ENV NRN=nrn-$NRN_VER

WORKDIR $HOME/packages
ADD http://www.neuron.yale.edu/ftp/neuron/versions/v$NRN_VER/$NRN.tar.gz .
RUN tar xzf $NRN.tar.gz; rm $NRN.tar.gz

RUN mkdir $VENV/build/$NRN

WORKDIR $VENV/build/$NRN
RUN $HOME/packages/$NRN/configure --with-paranrn --with-nrnpython=python3 --disable-rx3d --without-iv --prefix=$VENV > /dev/null
RUN make -j > /dev/null
RUN make install > /dev/null
RUN cd src/nrnpython; python3 setup.py install > /dev/null
RUN cd $VENV/bin; ln -s ../x86_64/bin/nrnivmodl; ln -s ../x86_64/bin/nrngui; ln -s ../x86_64/bin/nrnoc; ln -s ../x86_64/bin/nrniv

WORKDIR /home/docker/

# Install uncertainpy dependencies
RUN apt-get -y install xvfb hdf5-tools

RUN pip3 install coverage setuptools xvfbwrapper

# Make sure matplotlib uses agg
RUN mkdir .config/
RUN mkdir .config/matplotlib
RUN echo "backend : Agg" >> .config/matplotlib/matplotlibrc


RUN echo 'alias python="/usr/bin/python3"' >> /root/.bash_aliases && \
    echo 'alias pip="/usr/bin/pip3"' >> /root/.bash_aliases