FROM ubuntu:16.04


ENV HOME=/home/docker
RUN mkdir $HOME
WORKDIR $HOME

RUN apt-get update
RUN apt-get -y install python python-pip


# # Install uncertainpy and dependencies

# # # Uncertainpy dependencies
# RUN apt-get update --fix-missing

# RUN apt-get -y install texlive-latex-base texlive-latex-extra # texlive-fonts-recommended
# RUN apt-get -y install dvipng
# RUN apt-get -y install Xvfb
# RUN conda install -c conda-forge matplotlib
# RUN conda install -c anaconda seaborn
# RUN apt-get -y install h5utils
# # RUN apt-get -y install libx11-dev libxext-dev x11-apps


# RUN conda install -c conda-forge xvfbwrapper
# RUN conda install -c conda-forge multiprocess
# RUN conda install -c anaconda future

# # # Downgrade the pyqt package to solve a bug in anaconda
# # RUN conda install pyqt=4.11
# # RUN conda install -c anaconda pandas
# # RUN conda install -c anaconda seaborn




# RUN pip install elephant


# COPY . $HOME/uncertainpy
# WORKDIR $HOME/uncertainpy

# RUN cp -r tests/figures_docker/. tests/figures/.
# # RUN python setup.py install
