FROM continuumio/anaconda:latest

# Update anaconda in case the anaconda image is outdated
RUN conda update conda


# Install Nest and Neuron
ENV LANG=C.UTF-8

RUN apt-get update; apt-get install -y automake libtool build-essential openmpi-bin libopenmpi-dev \
                                       libncurses5-dev libreadline-dev libgsl0-dev cmake


ENV HOME=/home/docker
ENV VENV=$HOME/simulators
RUN mkdir $HOME; mkdir $HOME/packages; mkdir $VENV
ENV PATH=$PATH:$VENV/bin

ENV NEST_VER=2.14.0 NRN_VER=7.5
ENV NEST=nest-$NEST_VER NRN=nrn-$NRN_VER

WORKDIR $HOME/packages
# Once neurons certificate is properly set up use add again
# ADD http://www.neuron.yale.edu/ftp/neuron/versions/v$NRN_VER/$NRN.tar.gz .
RUN wget http://www.neuron.yale.edu/ftp/neuron/versions/v$NRN_VER/$NRN.tar.gz --no-check-certificate
ADD https://github.com/nest/nest-simulator/releases/download/v$NEST_VER/nest-$NEST_VER.tar.gz .
RUN tar xzf $NEST.tar.gz; tar xzf $NRN.tar.gz; rm $NEST.tar.gz $NRN.tar.gz


RUN mkdir $VENV/build; mkdir $VENV/bin
WORKDIR $VENV/build
RUN mkdir $NRN; \
    cd $NRN; \
    $HOME/packages/$NRN/configure --with-paranrn --with-nrnpython=python --disable-rx3d --without-iv --prefix=$VENV; \
    make; make install; \
    cd src/nrnpython; python setup.py install; \
    cd $VENV/bin; ln -s ../x86_64/bin/nrnivmodl; ln -s ../x86_64/bin/nrngui; ln -s ../x86_64/bin/nrnoc; ln -s ../x86_64/bin/nrniv


RUN mkdir $NEST; \
    cd $NEST; \
    cmake -DCMAKE_INSTALL_PREFIX=$VENV \
          -Dwith-mpi=ON  \
          -Dwith-python=2 \
          $HOME/packages/$NEST; \
    make; make install;



WORKDIR /home/docker/
RUN echo "source $VENV/bin/nest_vars.sh" >> .bashrc
# Add nest to python path
ENV PYTHONPATH $PYTHONPATH:/home/docker/simulators/lib/python2.7/site-packages/

RUN conda install libgcc



# Get X working

RUN touch /home/docker/.Xauthority
RUN apt-get update; apt-get install -y libx11-dev libxext-dev x11-apps
EXPOSE 22



# Install test coverage dependencies
RUN pip install coverage

# Install uncertainpy dependencies
RUN apt-get update --fix-missing
RUN apt-get -y install xvfb

RUN pip install xvfbwrapper


# Make sure matplotlib uses agg
RUN mkdir .config/
RUN mkdir .config/matplotlib
RUN echo "backend : Agg" >> .config/matplotlib/matplotlibrc


# Ensure newest version of Chaospy, only temporary
RUN git clone https://github.com/jonathf/chaospy.git
RUN cd chaospy; python setup.py install