#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _ca_spike1.ses_reg(void);
extern void _ca_spike2.ses_reg(void);
extern void _IKM_reg(void);
extern void _SlowCa_reg(void);
extern void _cad_reg(void);
extern void _h_reg(void);
extern void _kca_reg(void);
extern void _kfast_reg(void);
extern void _kslow_reg(void);
extern void _nap_reg(void);
extern void _nat_reg(void);
extern void _example1.hoc_reg(void);
extern void _example2.hoc_reg(void);
extern void _example3.hoc_reg(void);
extern void _*.inc_reg(void);
extern void _IKM.mod_reg(void);
extern void _SlowCa.mod_reg(void);
extern void _ca_spike1.ses.mod_reg(void);
extern void _ca_spike2.ses.mod_reg(void);
extern void _cad.mod_reg(void);
extern void _example1.hoc.mod_reg(void);
extern void _example2.hoc.mod_reg(void);
extern void _example3.hoc.mod_reg(void);
extern void _h.mod_reg(void);
extern void _kca.mod_reg(void);
extern void _kfast.mod_reg(void);
extern void _kslow.mod_reg(void);
extern void _mod_func.c_reg(void);
extern void _mosinit.hoc.mod_reg(void);
extern void _nap.mod_reg(void);
extern void _nat.mod_reg(void);
extern void _readme.html.mod_reg(void);
extern void _reduced_geometry_20com.hoc.mod_reg(void);
extern void _reduced_model.hoc.mod_reg(void);
extern void _regular_spiking.ses.mod_reg(void);
extern void _screenshot.png.mod_reg(void);
extern void _*.inc_reg(void);
extern void _IKM.mod_reg(void);
extern void _SlowCa.mod_reg(void);
extern void _ca_spike1.ses.mod_reg(void);
extern void _ca_spike2.ses.mod_reg(void);
extern void _cad.mod_reg(void);
extern void _example1.hoc.mod_reg(void);
extern void _example2.hoc.mod_reg(void);
extern void _example3.hoc.mod_reg(void);
extern void _h.mod_reg(void);
extern void _kca.mod_reg(void);
extern void _kfast.mod_reg(void);
extern void _kslow.mod_reg(void);
extern void _mod_func.c_reg(void);
extern void _mosinit.hoc.mod_reg(void);
extern void _nap.mod_reg(void);
extern void _nat.mod_reg(void);
extern void _readme.html.mod_reg(void);
extern void _reduced_geometry_20com.hoc.mod_reg(void);
extern void _reduced_model.hoc.mod_reg(void);
extern void _regular_spiking.ses.mod_reg(void);
extern void _screenshot.png.mod_reg(void);
extern void _mosinit.hoc_reg(void);
extern void _readme.html_reg(void);
extern void _reduced_geometry_20com.hoc_reg(void);
extern void _reduced_model.hoc_reg(void);
extern void _regular_spiking.ses_reg(void);
extern void _screenshot.png_reg(void);
extern void _*.inc_reg(void);
extern void _IKM.mod_reg(void);
extern void _SlowCa.mod_reg(void);
extern void _ca_spike1.ses.mod_reg(void);
extern void _ca_spike2.ses.mod_reg(void);
extern void _cad.mod_reg(void);
extern void _example1.hoc.mod_reg(void);
extern void _example2.hoc.mod_reg(void);
extern void _example3.hoc.mod_reg(void);
extern void _h.mod_reg(void);
extern void _kca.mod_reg(void);
extern void _kfast.mod_reg(void);
extern void _kslow.mod_reg(void);
extern void _mod_func.c_reg(void);
extern void _mosinit.hoc.mod_reg(void);
extern void _nap.mod_reg(void);
extern void _nat.mod_reg(void);
extern void _readme.html.mod_reg(void);
extern void _reduced_geometry_20com.hoc.mod_reg(void);
extern void _reduced_model.hoc.mod_reg(void);
extern void _regular_spiking.ses.mod_reg(void);
extern void _screenshot.png.mod_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," ca_spike1.ses.mod");
    fprintf(stderr," ca_spike2.ses.mod");
    fprintf(stderr," channels/IKM.mod");
    fprintf(stderr," channels/SlowCa.mod");
    fprintf(stderr," channels/cad.mod");
    fprintf(stderr," channels/h.mod");
    fprintf(stderr," channels/kca.mod");
    fprintf(stderr," channels/kfast.mod");
    fprintf(stderr," channels/kslow.mod");
    fprintf(stderr," channels/nap.mod");
    fprintf(stderr," channels/nat.mod");
    fprintf(stderr," example1.hoc.mod");
    fprintf(stderr," example2.hoc.mod");
    fprintf(stderr," example3.hoc.mod");
    fprintf(stderr," init_models_with_ca/*.mod");
    fprintf(stderr," init_models_without_ca/*.mod");
    fprintf(stderr," mosinit.hoc.mod");
    fprintf(stderr," readme.html.mod");
    fprintf(stderr," reduced_geometry_20com.hoc.mod");
    fprintf(stderr," reduced_model.hoc.mod");
    fprintf(stderr," regular_spiking.ses.mod");
    fprintf(stderr," screenshot.png.mod");
    fprintf(stderr," x86_64/*.mod");
    fprintf(stderr, "\n");
  }
  _ca_spike1.ses_reg();
  _ca_spike2.ses_reg();
  _IKM_reg();
  _SlowCa_reg();
  _cad_reg();
  _h_reg();
  _kca_reg();
  _kfast_reg();
  _kslow_reg();
  _nap_reg();
  _nat_reg();
  _example1.hoc_reg();
  _example2.hoc_reg();
  _example3.hoc_reg();
  _*.inc_reg();
  _IKM.mod_reg();
  _SlowCa.mod_reg();
  _ca_spike1.ses.mod_reg();
  _ca_spike2.ses.mod_reg();
  _cad.mod_reg();
  _example1.hoc.mod_reg();
  _example2.hoc.mod_reg();
  _example3.hoc.mod_reg();
  _h.mod_reg();
  _kca.mod_reg();
  _kfast.mod_reg();
  _kslow.mod_reg();
  _mod_func.c_reg();
  _mosinit.hoc.mod_reg();
  _nap.mod_reg();
  _nat.mod_reg();
  _readme.html.mod_reg();
  _reduced_geometry_20com.hoc.mod_reg();
  _reduced_model.hoc.mod_reg();
  _regular_spiking.ses.mod_reg();
  _screenshot.png.mod_reg();
  _*.inc_reg();
  _IKM.mod_reg();
  _SlowCa.mod_reg();
  _ca_spike1.ses.mod_reg();
  _ca_spike2.ses.mod_reg();
  _cad.mod_reg();
  _example1.hoc.mod_reg();
  _example2.hoc.mod_reg();
  _example3.hoc.mod_reg();
  _h.mod_reg();
  _kca.mod_reg();
  _kfast.mod_reg();
  _kslow.mod_reg();
  _mod_func.c_reg();
  _mosinit.hoc.mod_reg();
  _nap.mod_reg();
  _nat.mod_reg();
  _readme.html.mod_reg();
  _reduced_geometry_20com.hoc.mod_reg();
  _reduced_model.hoc.mod_reg();
  _regular_spiking.ses.mod_reg();
  _screenshot.png.mod_reg();
  _mosinit.hoc_reg();
  _readme.html_reg();
  _reduced_geometry_20com.hoc_reg();
  _reduced_model.hoc_reg();
  _regular_spiking.ses_reg();
  _screenshot.png_reg();
  _*.inc_reg();
  _IKM.mod_reg();
  _SlowCa.mod_reg();
  _ca_spike1.ses.mod_reg();
  _ca_spike2.ses.mod_reg();
  _cad.mod_reg();
  _example1.hoc.mod_reg();
  _example2.hoc.mod_reg();
  _example3.hoc.mod_reg();
  _h.mod_reg();
  _kca.mod_reg();
  _kfast.mod_reg();
  _kslow.mod_reg();
  _mod_func.c_reg();
  _mosinit.hoc.mod_reg();
  _nap.mod_reg();
  _nat.mod_reg();
  _readme.html.mod_reg();
  _reduced_geometry_20com.hoc.mod_reg();
  _reduced_model.hoc.mod_reg();
  _regular_spiking.ses.mod_reg();
  _screenshot.png.mod_reg();
}
